#' read a tar file into a list
#'
#' `read_tar()` will read in a `tar` file, zipped or not, and join `tsv` file(s)
#' in each directory. Internally, `tsv` file(s) are read in parallel using the
#' \code{\link{furrr}} package and \code{\link[readr]{read_tsv}}. When reading
#' from the `metaphlan_bugs_list` directory, the NCBI Taxonomy ID column is
#' skipped, and, if present, the `metadata` directory is ignored.
#'
#' @param tar_file A path to a tar file generated by the high load pipeline.
#'
#' @return A \code{\link[base]{list}} of \code{\link[base]{matrix}} elements.
#' @export
#'
#' @importFrom magrittr %>%
#' @importFrom stringr str_remove
#' @importFrom utils untar
#' @importFrom stringr str_subset
#' @importFrom purrr set_names
#' @importFrom purrr imap
#' @importFrom purrr map
#' @importFrom stringr str_remove
#' @importFrom purrr reduce
#' @importFrom dplyr full_join
#' @importFrom tibble column_to_rownames
#' @importFrom dplyr mutate
#' @importFrom dplyr across
#' @importFrom tidyr replace_na
read_tar <- function(tar_file) {
    dir_name <-
        base::basename(tar_file) %>%
        stringr::str_remove(".tar.gz")

    temp_dir <-
        base::tempdir()

    utils::untar(tar_file, exdir = temp_dir)

    base::file.path(temp_dir, dir_name) %>%
        base::dir() %>%
        stringr::str_subset("[^(metadata)]") %>%
        purrr::set_names() %>%
        purrr::imap(~ base::file.path(temp_dir, dir_name, .y)) %>%
        purrr::map(~ base::dir(path = .x, pattern = ".tsv", full.names = TRUE)) %>%
        purrr::map(~ purrr::set_names(.x, ~ base::basename(.x))) %>%
        purrr::map(~ purrr::set_names(.x, ~ stringr::str_remove(.x, ".tsv"))) %>%
        purrr::imap(~ read_tsv(.x, .y)) %>%
        purrr::map(~ purrr::reduce(.x, dplyr::full_join, by = "rowname")) %>%
        purrr::map(~ tibble::column_to_rownames(.x)) %>%
        purrr::map(~ dplyr::mutate(.x, dplyr::across(.fns = ~ tidyr::replace_na(.x, 0)))) %>%
        purrr::map(~ base::data.matrix(.x))
}
